# Clippy configuration
cognitive-complexity-threshold = 15
cyclomatic-complexity-threshold = 10
too-many-arguments-threshold = 8
too-many-lines-threshold = 300
type-complexity-threshold = 0
max-struct-bools = 3
max-fn-params-bools = 3
